### ISSUE TITLE
Fan Duct Modifications to Support Beacon RevH 

### ISSUE THREAD

**Issue by TheAZtech** [VzBoT3D/Vz-Printhead#8]
Beacon RevH is now an all in one design as the the silicone has been moved forward and the current duct design does not allow the Beacon to be mounted property. 

I am requesting to have the fan ducts that support Beacon modified to accept the new RevH design. 

Link to the STEP for the RevH: https://github.com/beacon3d/docs/blob/master/mcad/beacon/Beacon_RevH_Assm_LowProfile.STEP

Thank you for your great work and time! 

EDIT: Grammer

**Comment by pbsuper** [comment]
The ducts should be updated now and no longer hit the chip.
